awslabs/goformation

- generate/create-pull-request.sh
Updated create-pull-request script to work with a dedicated GitHub goformation user rather than my personal one
> Updated create-pull-request script 

- goformation.go
- goformation_test.go
- intrinsics/intrinsics.go
- intrinsics/intrinsics_test.go
This enables evaluating template with parameters other than the default ones
> Allow overriding template parameters via options

- README.md
- example/parse-yaml-template.go
- example/template.yaml
> Improved example that was failing

- intrinsics/intrinsics.go
- intrinsics/intrinsics_test.go
- vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
- vendor/github.com/imdario/mergo/LICENSE
- vendor/github.com/imdario/mergo/README.md
- vendor/github.com/imdario/mergo/doc.go
- vendor/github.com/imdario/mergo/map.go
- vendor/github.com/imdario/mergo/merge.go
- vendor/github.com/imdario/mergo/mergo.go
> Support Globals

- cloudformation/awsserverlessapi_definitionuri.go
- cloudformation/awsserverlessfunction_codeuri.go
- cloudformation/awsserverlessfunction_policies.go
- cloudformation/awsserverlessfunction_properties.go
- cloudformation/template.go
- generate/templates/polymorphic-property.template
- goformation_test.go
@PaulMaddox This applies the fix in #41 to the template files.
resolves https://github.com/awslabs/goformation/pull/40
resolves #67 
replaces https://github.com/awslabs/goformation/pull/41
> Handle null event sources and Transform keyword

- .travis.yml
- README.md
This PR adds support for semantic-release, to automatically tag new releases.
> Adding semantic-release

- test.go
New test feature, just to test automatic semantic releases. Expecting this to fail due to lack of
GitHub credentials.
> feat(lib): Test feature (please ignore)

- intrinsics/fnjoin.go
> More idiomatic implementation of Fn::Join

- .releaserc
- .travis.yml
*Issue #, if available:* #170 
Add [semantic-release](https://github.com/semantic-release/semantic-release) for automatic versioning.
> Add semantic release

- .travis.yml
> fix(CI): Update TravisCI configuration for semantic-release to use jobs

- .travis.yml
> fix(CI): only run semantic-release on push-to-master (not on pull requests)

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- cloudformation/resources/awsserverlessapplication_location.go
- schema/cloudformation.go
- schema/cloudformation.schema.json
- schema/sam.go
- schema/sam.schema.json
> Add contributing guidelines and code of conduct

- cloudformation/all.go
- cloudformation/resources/aws-apigatewayv2-apimapping.go
- cloudformation/resources/aws-apigatewayv2-domainname.go
- cloudformation/resources/aws-apigatewayv2-domainname_domainnameconfiguration.go
- cloudformation/resources/aws-batch-jobdefinition_containerproperties.go
- cloudformation/resources/aws-batch-jobdefinition_resourcerequirement.go
- cloudformation/resources/aws-cognito-userpool_emailconfiguration.go
- cloudformation/resources/aws-fsx-filesystem.go
- cloudformation/resources/aws-greengrass-functiondefinition_functionconfiguration.go
- cloudformation/resources/aws-greengrass-functiondefinitionversion_functionconfiguration.go
- cloudformation/resources/aws-greengrass-resourcedefinition.go
- cloudformation/resources/aws-greengrass-resourcedefinition_groupownersetting.go
- cloudformation/resources/aws-greengrass-resourcedefinition_localdeviceresourcedata.go
- cloudformation/resources/aws-greengrass-resourcedefinition_localvolumeresourcedata.go
- cloudformation/resources/aws-greengrass-resourcedefinition_resourcedatacontainer.go
- cloudformation/resources/aws-greengrass-resourcedefinition_resourcedefinitionversion.go
- cloudformation/resources/aws-greengrass-resourcedefinition_resourceinstance.go
- cloudformation/resources/aws-greengrass-resourcedefinition_s3machinelearningmodelresourcedata.go
- cloudformation/resources/aws-greengrass-resourcedefinition_sagemakermachinelearningmodelresourcedata.go
- cloudformation/resources/aws-greengrass-resourcedefinition_secretsmanagersecretresourcedata.go
- schema/cloudformation.go
- schema/cloudformation.schema.json
- schema/sam.go
- schema/sam.schema.json
> CloudFormation Updates

- cloudformation/intrinsics.go
#204 
If length of list is 1 assume that it's nested intrinsic and encode it in a different way.
> Fix Fn::Select + Fn::GetAZs

- go.mod
- go.sum
> fix(go): Ran `go mod tidy`

- .github/workflows/update_schema.yml
*Issue #, if available:* n/a
Testing GitHub Actions for auto-updating of schema
> Testing GitHub Actions for auto-updating of schema

- cloudformation/all.go
- generate/generate.go
*Issue #, if available:* n/a
Previously items in the cloudformation/all.go file were generated in a
random order, which meant the generated file was likely to change each
and every time it was generated - even if the contents were the same.
> fix(schema): Ordered cloudformation/all.go file

- cloudformation/appmesh/aws-appmesh-mesh.go
> feat(schema): AWS CloudFormation Update (2019-10-29)

- goformation_test.go
*Issue #, if available:* n/a
Created tests for README examples. This will cause build failures in CI if for any reason our examples stop compiling/working in the future.
ala https://blog.golang.org/examples
> chore(docs): Created tests for README examples

- goformation_test.go
- test/json/resource-with-tags.json
*Issue #, if available:* issue #223
Added a test to try and replicate the issue reported in #223 (parsing fails of JSON template contains tags). Could not replicate, but might as well keep the test to avoid future regressions.
> chore(tests): Added a test for JSON resource tags

- cloudformation/template.go
*Issue #220 *
This PR adds the Parameter type as defiened in #220.
> Add CloudFormation parameter type

- cloudformation/acmpca/aws-acmpca-certificate.go
- cloudformation/acmpca/aws-acmpca-certificateauthority.go
- cloudformation/acmpca/aws-acmpca-certificateauthorityactivation.go
- cloudformation/all.go
- cloudformation/cognito/aws-cognito-userpool.go
- cloudformation/cognito/aws-cognito-userpool_accountrecoverysetting.go
- cloudformation/cognito/aws-cognito-userpool_recoveryoption.go
- cloudformation/transfer/aws-transfer-server_endpointdetails.go
- schema/cloudformation.go
- schema/cloudformation.schema.json
- schema/sam.go
- schema/sam.schema.json
Updated the following AWS CloudFormation resources:
- AWS::Cognito::UserPool
- AWS::ACMPCA::Certificate
- AWS::ACMPCA::CertificateAuthorityActivation
- AWS::ACMPCA::CertificateAuthority
- AWS::Cognito::UserPool.RecoveryOption
- AWS::Transfer::Server.EndpointDetails
- AWS::Cognito::UserPool.AccountRecoverySetting
> feat(schema): CloudFormation Updates (2020-01-30)

- cloudformation/appmesh/aws-appmesh-route_grpcroute.go
- cloudformation/appmesh/aws-appmesh-route_grpctimeout.go
- cloudformation/appmesh/aws-appmesh-route_httproute.go
- cloudformation/appmesh/aws-appmesh-route_httptimeout.go
- cloudformation/appmesh/aws-appmesh-route_tcptimeout.go
- cloudformation/appmesh/aws-appmesh-virtualnode_duration.go
- cloudformation/appmesh/aws-appmesh-virtualnode_grpctimeout.go
- cloudformation/appmesh/aws-appmesh-virtualnode_httptimeout.go
- cloudformation/appmesh/aws-appmesh-virtualnode_listener.go
- cloudformation/appmesh/aws-appmesh-virtualnode_listenertimeout.go
- cloudformation/appmesh/aws-appmesh-virtualnode_tcptimeout.go
- cloudformation/ssm/aws-ssm-maintenancewindow.go
- schema/cloudformation.go
- schema/cloudformation.schema.json
- schema/sam.go
- schema/sam.schema.json
*Issue #, if available:* Fixes #283 
Update CFN resources
> CFN Updates

- .github/workflows/update_schema.yml
> chore(ci): improve CI for schema updates

- cloudformation/intrinsics.go
> Allow for int in Eqauls

- cloudformation/template.go
Regarding documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html Output should have Condition property
> Add condition property to outputs

- .github/workflows/codeql-analysis.yml
*Description of changes:* adds CodeQL analysis.
> ci(codeql): add codeql analysis

- .github/workflows/test_pull_request.yml
*Description of changes:* used latest version of actions, and added tests on major golang versions
> ci(pull_requests): improved checks with multiple golang versions

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/test_pull_request.yml
- .github/workflows/update_schema.yml
*Description of changes:* update CI
> ci: update to latest versions

- cloudformation/serverless/aws-serverless-function_sampolicytemplate.go
- generate/sam-2016-10-31.json
Related issue in aws-toolkit-vscode: https://github.com/aws/aws-toolkit-vscode/issues/2018
This PR adds in DynamoDBWritePolicy into the sam policy template
DynamoDBWritePolicy aws documentation: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#dynamo-db-write-policy
> fix(schema): Add DynamoDBWritePolicy to sam policy template

- cloudformation/serverless/aws-serverless-function_sampolicytemplate.go
- generate/sam-2016-10-31.json
Related schema issue in aws-toolkit-vscode: https://github.com/aws/aws-toolkit-vscode/issues/2502
This PR adds in S3WritePolicy to the sam policy template.
The aws documentation for S3WritePolicy can be found here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html#s3-write-policy
> fix(schema): Add S3WritePolicy to sam policy template

- cloudformation/intrinsics.go
https://github.com/awslabs/goformation/issues/469
> Add intrinsics ptr versions

- cloudformation/intrinsics.go
https://github.com/awslabs/goformation/issues/471
> feat(if intrinsics): generalized solution to support more types

- cloudformation/serverless/aws-serverless-function_iampolicydocument.go
- cloudformation/serverless/aws-serverless-function_scheduleevent.go
- generate/sam-2016-10-31.json
*Issue #, if available:* #477
Same as #477 but renamed the commit message.
> feat(sam): add missing fields to ScheduledEvents and remove required versions from IAM

- cloudformation/global/api.go
- cloudformation/serverless/aws-serverless-api.go
- generate/sam-2016-10-31.json
*Closes #576*
*Adds AlwaysDeploy option to AWS::Serverless::Api*
> feat(serverless): add AlwaysDeploy option
