awslabs/goformation

README.md, cloudformation/awsserverlessfunction_stringoriampolicydocumentorlistofstringorlistofiampolicydocument.go, cloudformation/awsserverlessfunction_stringorlistofstring.go, generate/templates/polymorphic-property.template, goformation.go, goformation_test.go, intrinsics/fnbase64.go, intrinsics/fnfindinmap.go, intrinsics/fnjoin.go, intrinsics/fnselect.go, intrinsics/fnsplit.go, intrinsics/fnsub.go, intrinsics/intrinsics.go, intrinsics/intrinsics_test.go, intrinsics/ref.go, test/yaml/yaml-intrinsic-tags.yaml
Updated the intrinsic function handler signature to include the full template `interface{}`. This will allow us to do lookups on other resources should we want to implement `!Ref` at a later date.
Intrinsic function handlers now have the signature:
```go
func handle(name string, input interface{}, template interface{}) interface{} { 
// name is the intrinsic function type, such as Fn::Join
// input is the resource it needs to perform the intrinsic function on
// template is a reference to the whole template data
// return value is the result of the intrinsic function processing that this method
// does, and will be placed in the template where the intrinsic function was.
}
```
=> Implemented most of the intrinsic functions

goformation.go, goformation_test.go, intrinsics/intrinsics.go, intrinsics/intrinsics_test.go, intrinsics/ref.go, intrinsics/tags.go
I think this makes for a neater API if we move the intrinsic tag handling to the intrinsics package. 
It also means all YAML->JSON conversion can be done in the intrinsics package too.
```go
intrinsics.ProcessYAML(data, opts)
intrinsics.ProcessJSON(data, opts)
```
=> Moved tag parsing to the intrinsics package

goformation_test.go, intrinsics/fnsub.go, intrinsics/intrinsics_test.go, intrinsics/ref.go
If Fn::Sub is an array, then do named string replacements, ala:
`{ "Fn::Sub": [ "some ${replaced}", { "replaced": "value" } ] }`
If Fn::Sub is a string, then resolve any ${Reference}'s in it:
`{ "Fn::Sub": "some-string-with-a-${variable}" }`
Note: This just calls the Fn::Ref intrinsic function to resolve references, so there is no code duplication. Also wrote a bunch of test cases to cover this.
Fixes #14.
=> Fn::Sub now resolves references when it needs to

intrinsics/fngetatt.go, intrinsics/fnsub.go, intrinsics/intrinsics_test.go
Made Fn::Sub check if a reference is a normal reference, or if it has a. in it, then treat it as a reference attribute lookup and pass it to
Fn::GetAtt. While Fn::GetAtt isn't implemented today, this will make
Fn::Sub "just work" when it is one day implemented. Thanks sanathkr@ for
this suggestion!
=> Better Fn::Sub (calls Fn::GetAtt when required)

.travis.yml, README.md, generate/create-pull-request.sh
Added a travis script that checks on a daily basis for any AWS CloudFormation updates (comparing against master branch), and if any are found, create a new pull request for them automatically.
If more changes come in before the pull request is closed/merged, the commits will be added to the pull request.
I've tested this pretty extensively in my own fork, however as all it does is open PRs, the worse that could happen is we get a few odd PR's generated over the next few days.
=> Auto-updating of GoFormation resources

vendor/github.com/onsi/gomega/gstruct/elements.go, vendor/github.com/onsi/gomega/gstruct/errors/nested_types.go, vendor/github.com/onsi/gomega/gstruct/fields.go, vendor/github.com/onsi/gomega/gstruct/ignore.go, vendor/github.com/onsi/gomega/gstruct/pointer.go, vendor/github.com/onsi/gomega/gstruct/types.go, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/LICENSE.libyaml, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go, vendor/gopkg.in/yaml.v2/yamlprivateh.go, vendor/vendor.json
Our testing library Gomega) requires the yaml.v2 package, so vendoring
it back in. This wasn't picked up in travisci builds as that
automatically tries to fetch any missing dependencies at build time.
This shouldn't have any impact on goformation, as we specifically
reference github.com/sanathkr/go-yaml etc.
=> Fixing yaml.v2 vendoring

README.md, intrinsics/fngetazs.go, intrinsics/fnselect.go, intrinsics/intrinsics.go, intrinsics/intrinsics_test.go
This also changes the Fn::Select intrinsic to support specifying the index as a string.
Saw this form used in CloudFormation [documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html#w2ab2c21c28c33c17):
```javascript
{"Fn::Select" : [ "0", { "Fn::GetAZs" : "" } ]}
```
=> Add support for Fn::GetAZs intrinsic

generate/templates/schema-resource.template, goformation_schema_test.go, schema/cloudformation.schema.json, schema/sam.schema.json, test/json/valid-template-resource-attributes.json
Added strict schema for DependsOn, Metadata, and DeletionPolicy, and added loose schema for CreationPolicy and UpdatePolicy.
Reference:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-product-attribute-reference.html
=> Support for resource attributes in CloudFormation JSON schema

intrinsics/fnjoin.go, intrinsics/intrinsics_test.go
Fn::Join now works as per CloudFormation specification, and covers the following two use cases:
`"Fn::Join": [ "apples", "pears" ]` which results in `applespears` 
`"Fn::Join": [ "-", [ "apples", "pears" ] ]` which results in `apples-pears` 
This fixes #92
=> Improvements to Fn::Join

cloudformation/aws-serverless-api.go, generate/sam-2016-10-31.json, schema/sam.go, schema/sam.schema.json, test/yaml/aws-serverless-api.yaml
Serverless::API allows MethodSettings to pass through to control things like LoggingLevel. This fixes Goformation to allow those settings through rather than dropping them when processing a Serverless::API resource.
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapi
=> Support MethodSettings on Serverless::API

goformation_test.go, intrinsics/intrinsics.go, intrinsics/intrinsics_test.go
I needed this for something I'm writing. Beats copying the custom tag unmarshaller code out of `intrinsics/intrinsics.go`.
This basically allows someone to use `OpenWithOptions` to get a template object that represents the unresolved original (`Ref`s intact, etc.)
=> Add option to disable intrinsics processing

cloudformation/policies.go, cloudformation/policies_test.go
As mentioned in issue [#130](https://github.com/awslabs/goformation/issues/130) there was a typo on the name of a property of the CloudFormation's attribue "CreationPolicy".
You can check the official [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html).
=> fix property name in CreationPolicy

generate/generate.go, schema/cloudformation.go, schema/sam.go
I want to be able to use the generated json schema from the `schema` package but it needs to be public by `Title`izing the string.
Also ran `go generate` which caused a bunch of updates.
For unknown reason `aws-servicediscovery-instance.go` incorrectly assigned the type `Map` instead of interface. I have manually overridden but may look into later.
=> [Fix] Make the generated schema public + generate

generate/templates/resource.template
All resources have the `"additionalProperties": false` property in the schema as they do not allow unknown properties. This PR enforces that while unmarshalling any JSON or YML resource.
=> [Feature] Raise error on unknown property

generate/templates/resource.template
By returning pointers from the generated code users are able change the resources attributes before they are sent to cloud formation. e.g.:
```
template, _ := goformation.Open("template.yaml")
function, _ := template.GetAWSServerlessFunctionWithName("FunctionName")
function.FunctionName = "edit-the-name"
template.YAML()
```
Previously, this would not have worked for two reasons:
1. The found instance did not replace the `map[string]interface{}` in `template.Resources`
2. The returned instance was a Struct not a reference.
=> [Refactor] Return pointers from template.Resources finder methods

cloudformation/intrinsics.go, cloudformation/intrinsics_test.go, intrinsics/tags.go
I like the way in which this project encodes the CloudFormation Intrinsic functions to base64 to remain valid within the JSON schema.
I wanted to be able to parse a YAML, edit some attributes in Go, then go to JSON. This required intrinsic handlers to encode to base64.
This reuses the intrinsics encoders in the cloudformation package, wraps their functions and builds the intrinsic handler overrides.
I think in the future I will improve and repackage the intrinsics into a parser package, so that these different handler overrides can be there. 
Ultimately I would like to try reimplement something like https://github.com/awslabs/aws-cfn-template-flip using this library. Though that might be a way off.
=> [Feature] Intrinsics handlers to encode to Base64

generate/sam-2016-10-31.json
Fixng #162. 
Updating the SAM template file so that after generating the newer features of SAM are available. 
I am not sure if this file is mastered in this repository. If there is a better version internally of the SAM template, please replace.
I did not go all out with some of the definitions as I couldn't find very good documents on their acceptable format (e.g. Auth).
=> [Update] sam json template to add newly available features

.travis.yml
=> fix(CI): fix broken GitHub PR integration (maybe)

cloudformation/resources/aws-serverless-api.go, cloudformation/resources/aws-serverless-function.go, cloudformation/resources/aws-serverless-function_dynamodbevent.go, cloudformation/resources/aws-serverless-function_kinesisevent.go, cloudformation/resources/aws-serverless-function_sqsevent.go, generate/sam-2016-10-31.json, schema/sam.go, schema/sam.schema.json
A few additional primitive typed properties were added to SAM in the last few months. This adds them to the classes. Also with code generation.
=> [Update] updates some primitive types from SAM spec

cloudformation/custom_resource.go, cloudformation/template.go, goformation_test.go, test/yaml/custom-resource.yaml
#193 
This PR lets goformation Marshal and Unmarshal `Custom::*` resources. This is a pretty minimal change but allows for a lot more functionality. 
=> [Feature] Allow custom resources to be defined and parsed

cloudformation/serverless/aws-serverless-api.go, generate/sam-2016-10-31.json, schema/sam.go, schema/sam.schema.json, test/yaml/aws-serverless-api.yaml
https://github.com/awslabs/goformation/issues/242
This sets the MethodSettings to a list of objects
https://github.com/awslabs/serverless-application-model#1170
=> [Fix] MethodSettings in serverless API gateway

cloudformation/serverless/api_cors.go, cloudformation/serverless/aws-serverless-api.go, cloudformation/serverless/aws-serverless-api_corsconfiguration.go, generate/sam-2016-10-31.json, goformation_test.go, schema/sam.go, schema/sam.schema.json, test/yaml/aws-serverless-api-string-or-cors-configuration.yaml
*Issue #, if available:* fixes #244 
*Description of changes:* AWS::Serverless::Api.Cors should be either a string, or a [cors configuration object](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cors-configuration).
=> fix(schema): AWS::Serverless:Api.Cors

test/yaml/aws-serverless-function-env-vars.yaml, test/yaml/sam-official-samples/s3_processor/template.yaml
CloudFormation templates in goformation have been found to include a [deprecated Lambda function runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) (nodejs6.10). The affected templates have been updated to a supported runtime (nodejs10.x).
Please note, **this pull request has been generated by a bot**; please check the base branch and files changed before merging.
=> Upgrade deprecated runtime nodejs6.10

test/json/invalid-sam-template-wrong-transform.json, test/json/valid-sam-template.json, test/json/valid-template-with-fns.json, test/yaml/aws-serverless-function-api-event.yaml, test/yaml/codestar/nodejs.yml, test/yaml/sam-official-samples/alexa_skill/template.yaml, test/yaml/sam-official-samples/api_backend/template.yaml, test/yaml/sam-official-samples/api_swagger_cors/template.yaml, test/yaml/sam-official-samples/codestar-node4.3.yaml, test/yaml/sam-official-samples/inline_swagger/template.yaml, test/yaml/sam-official-samples/iot_backend/template.yaml, test/yaml/sam-official-samples/schedule/template.yaml, test/yaml/sam-official-samples/stream_processor/template.yaml, test/yaml/sam-official-samples/templates/basic.yaml, test/yaml/sam-official-samples/templates/wrong.yaml
CloudFormation templates in goformation have been found to include a [deprecated Lambda function runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) (nodejs4.3). The affected templates have been updated to a supported runtime (nodejs10.x).
Please note, **this pull request has been generated by a bot**; please check the base branch and files changed before merging.
=> Upgrade deprecated runtime nodejs4.3

cloudformation/intrinsics.go, cloudformation/intrinsics_test.go
`!GetAtt` was incorrectly encoding, it should have used a delimiter `.` to split a string into two arguments.
=> [Fix] Properly Encode !GetAtt yaml tag

cloudformation/template.go, generate/templates/schema.template, goformation_test.go, schema/cloudformation.go, schema/cloudformation.schema.json, test/yaml/transform-multiple.yaml, test/yaml/transform-single.yaml
*Issue #, if available:* 
#267
Transform field can be String or Array of Strings, this fixes json schema and UnmarshalJSON.
UnmarshalJSON needs fix because it receives []interface{} instead of []string. Added additional case to handle this issue. Covered by two YAML template tests.
=> Align Transform field format with actual Cloudformation support

cloudformation/serverless/aws-serverless-function_cloudwatchlogsevent.go, cloudformation/serverless/function_properties.go, generate/sam-2016-10-31.json, go.mod, go.sum, schema/sam.go, schema/sam.schema.json
This adds the CloudWatchLogs event to Function
=> [Feature] adding the cloudwatch logs event to from SAM

intrinsics/fnsub.go
#274, #202 
Adds `:` character to regex for variable match, allowing all AWS pseudo parameters to be replaced
=> fix(intrinsics): change Fn::Sub to allow AWS pseudo parameters

cloudformation/policies/policies.go, generate/templates/resource.template, generate/templates/schema-resource.template
Add UpdateReplacePolicy to templates and policies so that it is generated for every resource.
As defined in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html
Add UpdateReplacePolicy to templates and policies so that it is generated for every resource.
=> Add UpdateReplacePolicy to all resources

cloudformation/serverless/aws-serverless-api.go, generate/sam-2016-10-31.json
*Issue:* #280
Added OpenApiVersion field to AWS::Serverless::Api resource
=> feat(schema): Add OpenApiVersion field to serverless Api

cloudformation/serverless/aws-serverless-function_eventbridgeruleevent.go, cloudformation/serverless/function_properties.go, generate/sam-2016-10-31.json
Added support for EventBridgeRule Event.
=> Serverless eventbridgeruleevent

cloudformation/serverless/aws-serverless-function_destinationconfig.go, cloudformation/serverless/aws-serverless-function_dynamodbevent.go, cloudformation/serverless/aws-serverless-function_onfailure.go, generate/sam-2016-10-31.json, schema/sam.go, schema/sam.schema.json
Update the DynamoDBEvent structs to reflect the new options found in the SAM spec here: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#dynamodb
=> Update DynamoDBEvent options as per the SAM spec

cloudformation/all.go, cloudformation/serverless/aws-serverless-function.go, cloudformation/serverless/aws-serverless-function_filesystemconfig.go, cloudformation/serverless/aws-serverless-statemachine.go, cloudformation/serverless/aws-serverless-statemachine_apievent.go, cloudformation/serverless/aws-serverless-statemachine_cloudwatcheventevent.go, cloudformation/serverless/aws-serverless-statemachine_cloudwatchlogsloggroup.go, cloudformation/serverless/aws-serverless-statemachine_eventbridgeruleevent.go, cloudformation/serverless/aws-serverless-statemachine_eventsource.go, cloudformation/serverless/aws-serverless-statemachine_functionsampt.go, cloudformation/serverless/aws-serverless-statemachine_iampolicydocument.go, cloudformation/serverless/aws-serverless-statemachine_logdestination.go, cloudformation/serverless/aws-serverless-statemachine_loggingconfiguration.go, cloudformation/serverless/aws-serverless-statemachine_s3location.go, cloudformation/serverless/aws-serverless-statemachine_sampolicytemplate.go, cloudformation/serverless/aws-serverless-statemachine_scheduleevent.go, cloudformation/serverless/aws-serverless-statemachine_statemachinesampt.go, cloudformation/serverless/statemachine_definitionuri.go, cloudformation/serverless/statemachine_policies.go, cloudformation/serverless/statemachine_properties.go, generate/sam-2016-10-31.json, schema/sam.go, schema/sam.schema.json
This PR adds step functions via `AWS::Serverless::StateMachine` to the SAM template and generated code
This PR also adds `FileSystemConfigs` ([see](https://aws.amazon.com/blogs/compute/using-amazon-efs-for-aws-lambda-in-your-serverless-applications/)) to `AWS::Serverless::Function`
=> [Feature] adding AWS::Serverless::StateMachine and FileSystemConfigs to Function

cloudformation/autoscaling/aws-autoscaling-autoscalinggroup.go, cloudformation/cloudformation/aws-cloudformation-waitcondition.go, cloudformation/ec2/aws-ec2-instance.go, cloudformation/intrinsics.go, cloudformation/intrinsics_test.go, cloudformation/lambda/aws-lambda-alias.go, generate/templates/resource.template
This PR:
1. adds the Change and Update policies to the Unmarshal method, then runs `go generate`. Without this change we get an unmarshal error for resources with these policies.
2. fixes intrinsic encoding incorrectly if an argument contains something needing escaping, e.g. if the !Sub has a new line in it.
3. fixes GetAtt decoding if it is a JSON fn::GetAtt
=> [Fix] Add Change and Update policies to the Unmarshal method

cloudformation/template.go, test/yaml/yaml-intrinsic-tags.yaml
#75 #135 
Cloudformation description: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
=> Add support for Template Outputs

generate/generate.go, generate/property.go
*Issue #, if available:* #300
If the CloudFormation Resource Specification has a resource property
that does not include any type information then this should be a
breaking error and generation should fail.
=> fix(generator): Check for properties with no type in CFN spec

.github/workflows/update_schema.yml, generate/generate.go, generate/property.go
*Issue #, if available:* #300 
If a resource property is missing a type in the CloudFormation Resource
Specification (see #300), then autofix it to type = 'Json', which will
in turn set it to interface{} in the generated Go structs.
=> chore(generator): autofix missing property types

cloudformation/intrinsics.go
*Issue #308, #282 
Tbh I do not found a better solution to fix that problem - also it will help to be compatible backward. Read more here - https://stackoverflow.com/questions/50560729/fnsub-expression-does-not-resolve-to-a-string
=> Fix Join function to allow to use parameters of type `List<>`

cloudformation/serverless/aws-serverless-layerversion.go, cloudformation/serverless/aws-serverless-layerversion_s3location.go, cloudformation/serverless/layerversion_contenturi.go, generate/sam-2016-10-31.json, schema/sam.go, schema/sam.schema.json
*Issue #, if available:* fixes #337
*Description of changes:* 
Support either S3Location or String for AWS::Serverless::LayerVersion.ContentUri
=> Sam layerversion contenturi

cloudformation/template.go, goformation_test.go
The field Export of the type Output should be a pointer,
otherwise it would produce invalid output, by adding
an empty struct to the export field:
```
Outputs:
VpcId:
Export: {}
```
This empty struct will cause a template validation error:
"Template format error: Output VpcId is malformed.
The Name field of every Export member is required."
Closes #294 
=> Field Export on type Output should be pointer

cloudformation/custom_resource.go, goformation_test.go
=> Add DependOn, DeletionPolicy and others to CustomResource

cloudformation/intrinsics.go, intrinsics/fntransform.go, intrinsics/intrinsics.go
Issue: #335 and refers also to #332 
Thanks to that implementation I can use Macros in my code. Example
- Macro code https://github.com/aws-cloudformation/aws-cloudformation-macros/blob/master/StringFunctions/string.yaml
- My code example - where `${Environment}` is uppercase and I would like to convert it to Lower using TransformFn
```
S3Bucket: cloudformation.TransformFn("String", map[string]string{
"InputString": cloudformation.Sub("mybucket.${Environment}"),
"Operation":   "Lower",
}),
````
=> Add cloudformation.TransformFn()

README.md
No existing issue
I noticed that the pseudo parameters page linked in the "Resolving References" section of the README appears to have moved.
Currently the link directs documentation of the `Ref` function. The pseudo parameters and examples are on a different page.
This commit updates the link to reference the pseudo parameters page.
As both links reference the same page, this commit consolidates both to one link.
=> Update README Resolving References link

cloudformation/intrinsics.go
Cloduformation.If should not able to accept strings but much more complex structs also - example:
```
Policy: cloudformation.If("PrivateApiGateway",
map[string]interface{}{
"Version": "2012-10-17",
"Statement": []map[string]interface{}{
{
"Effect":    "Allow",
"Principal": "*",
"Action":    "execute-api:Invoke",
"Resource":  cloudformation.Sub("arn:aws:execute-api:${AWS::Region}:${AWS::AccountId:*/*"),
},
},
},
map[string]interface{}{},
)
```
=> Improve cloudformation If to accept structs

cloudformation/serverless/aws-serverless-function_apievent.go, cloudformation/serverless/aws-serverless-function_auth.go, cloudformation/serverless/aws-serverless-function_authresourcepolicy.go, generate/sam-2016-10-31.json, goformation_test.go, schema/sam.go, schema/sam.schema.json
Updates sam schema file with description of [Function Auth Object](https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#function-auth-object) and generates the go code for the change.
=> Add AWS::Serverless::Function.Auth

generate/sam-2016-10-31.json
Removing required properties from AWS::Serverless::Function resources in order to support Serverless functions using Container Images. For reference, the image below was generated via SAM CLI, is using the latest SAM schema from the Goformation repo, and is syntactically correct.
=> Remove required properties from AWS::Serverless::Function

cloudformation/custom_resource.go
This adds the `Version` field to the Custom Cloudformation resource types which is supported according to the examples in the docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html
(For some reason the field is not properly documented in the above docs, only shown in the example).
Without this change you get an error:
```
json: unknown field \"Version\"
```
If you try to parse a Cloudformation template with the `Version` field defined.
Additionally I removed the `fmt.Printf` as the error is already returned from the function, so there is no need to print it as well. (Looks like left over debug printing).
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> Support Version field in custom resource

cloudformation/template.go
According to the docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html The `AllowedValues` field can be an array of any type, not just `string`. Therefore use `[]interface{}` for the type.
A simple example where it doesn't work before this change is if you define a parameter like this:
```yaml
LogsRetentionInDays:
Description: >-
Specifies the number of days you want to retain log events in the
log group for the Lambda function
Type:    Number
Default: 14
AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
```
Where it would fail with the error:
```
json: cannot unmarshal number into Go struct field Parameter.Parameters.AllowedValues of type string
``` …
=> Use any type for AllowedValues

cloudformation/serverless/aws-serverless-function_eventinvokeconfig.go, cloudformation/serverless/aws-serverless-function_eventinvokedestinationconfig.go, generate/sam-2016-10-31.json, schema/sam.go, schema/sam.schema.json
*Issue #, if available:* 
https://github.com/awslabs/goformation/issues/404
Added a new type called EventInvokeDestinationCOnfig with OnSUccess and OnFailure properties. Removed OnSuccess from existing DestinationConfig. Updated EventInvoke to use EventInvokeDestinationConfig
=> fix(sam): DestinationConfig shouldn't contain OnSuccess property

cloudformation/intrinsics.go
Fix #412
412
Format strings as %q, not %v if they're base64 encoded strings, coming as a result of other intrinsic functions.
=> feat: add support for base64 encoded string in instrinsic if function

cloudformation/intrinsics.go, goformation_test.go
I believe would help with https://github.com/awslabs/goformation/issues/265, though my use case was slightly different.
I couldn't figure out how to do Sub() with replacement variables, so I added a method that will expand to:
```
{ "Fn::Sub" : [ String, { Var1Name: Var1Value, Var2Name: Var2Value } ] }
```
=> Add SubVars to Sub with replacement variables

cloudformation/all.go, cloudformation/cdkmetadata/aws-cdkmetadata-cdkmetadata.go, cloudformation/template.go, goformation.go, goformation_test.go, intrinsics/intrinsics.go, test/yaml/cdkmetadata.yaml
https://github.com/awslabs/goformation/issues/334
Adding CDKMetada as new resource.
=> Adding cdkmetada resource

cloudformation/global/function.go, cloudformation/serverless/aws-serverless-function.go, generate/sam-2016-10-31.json, goformation_test.go
ARM64 support (https://github.com/aws/serverless-application-model/issues/2166) was added to SAM a few month ago in https://github.com/aws/serverless-application-model/pull/2164
This pull request brings the `Architectures` field to goformation's SAM spec.
=> Add architectures support for sam functions

generate/sam-2016-10-31.json
The `Architectures` property from `AWS::Serverless::Function` doesn't have a `PrimitiveItemType`. Instead, it has a `"ItemType": "String"`. This is preventing the CDK from generating the new L1 constructs for SAM.
Change `ItemType` to `PrimitiveItemType`.
=> fix(sam): AWS::Serverless::Function Properties Architectures property should have a primitive type specified

generate/sam-2016-10-31.json
*Issue #
A String needs to be a PrimitiveItemType instead of ItemType. ItemType means it's a complex property, which String isn't.
=> fix(schema): string should be a primitivetype

generate/generate.go, generate/property.go, generate/sam-2016-10-31.json, generate/templates/polymorphic-property.template, generate/templates/schema-property.template
related aws-toolkit-vscode issue: https://github.com/aws/aws-toolkit-vscode/issues/2440
Currently, when generating an array of item types the generator outputs all item types in one giant "anyOf". In some cases, this leads to incorrect schema validation since occasionally arrays can have multiple item types associated with the same array instance.
E.g.
```
test:
- false
- hello
- 0
```
This PR adds in support for "inclusive" item types. An "inclusive" item type is one that can be combined with other inclusive item types to allow multiple different item types in a single array, rather then having an array be one item type per instance. 
For example, right now in aws-toolkit-vscode yaml such as:
```
AWSTemplateFormatVersion: '2010-09-09' …
```
=> feat(schema): Support generation of array items with multiple item types

cloudformation/serverless/aws-serverless-function_iampolicydocument.go, cloudformation/serverless/aws-serverless-statemachine_iampolicydocument.go, generate/sam-2016-10-31.json
Related issue in aws-toolkit-vscode: https://github.com/aws/aws-toolkit-vscode/issues/1974
This PR adds in the version property into IAMPolicyDocument and fixes the type of Statement (should be array of json, not just json).
Version aws documentation: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_version.html
Statement aws documentation: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_statement.html
=> fix(schema): Add Version property into IAMPolicyDocument and fix Statement type

generate/templates/schema.template
Related issue in aws-toolkit-vscode: https://github.com/aws/aws-toolkit-vscode/issues/1978
This PR adds in support for custom resources in the format of `Custom::MyCustomResourceTypeName` as shown in the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html). From what I can tell, the unmarshalling of the Custom resource is already supported on the golang side in https://github.com/awslabs/goformation/blob/master/cloudformation/template.go#L125 so this just changes the JSON schemas.
=> feat(schema): Support custom resource types

generate/templates/schema-resource.template
Related aws-toolkit-vscode issue: https://github.com/aws/aws-toolkit-vscode/issues/1978
This PR adds in support for condition properties in resources, essentially allowing something like:
```
Resources:
MountPoint:
Type: "AWS::EC2::VolumeAttachment"
Condition: CreateProdResources
Properties:
InstanceId: !Ref EC2Instance
VolumeId: !Ref NewVolume
Device: /dev/sdh
```
from the [aws documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-condition.html) to be valid in JSON.
The above example was taken from: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-sample-templates.html
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> feat(schema): Support condition properties in resources

cloudformation/serverless/aws-serverless-api_auth.go, generate/sam-2016-10-31.json
Related issue in aws-vscode-toolkit: https://github.com/aws/aws-toolkit-vscode/issues/2627
This PR just adds in AddDefaultAuthorizerToCorsPreflight according to the spec at https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api-auth-object
=> fix(schema): Add AddDefaultAuthorizerToCorsPreflight to Serverless Auth

cloudformation/serverless/aws-serverless-httpapi_corsconfigurationobject.go, generate/sam-2016-10-31.json, goformation_test.go, test/yaml/aws-serverless-http-api-cors-configuration.yaml
https://github.com/awslabs/goformation/issues/403 
Fix CorsConfiguration for AWS::Serverless::HttpApi,
- AllowMethods/AllowHeaders/AllowOrigins properties are `List` instead of `String`.
- allow-origin property is `AllowOrigins` not `AllowOrigin`
- `MaxAge` property is `Integer` instead of `String`
Note: Current definition seems to be the same as [`CorsConfiguration for AWS::Serverless::Api`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html) but they are incorrect.
Ref:
HttpApiCorsConfiguration
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-httpapi-httpapicorsconfiguration.html
Cors Configuration Object …
=> feat(schema): serverless http api cors configuration

cloudformation/policies_test.go, cloudformation/template.go, go.mod, goformation_test.go, intrinsics/intrinsics.go, intrinsics/tags.go, test/yaml/sam-official-samples/inline_swagger/template.yaml
*Issue #, if available:* #534
This PR bumps go-yaml version to the latest avaialble. This meant that the custom intrinstics parser had to be re-written to accomodate the API changes on go-yaml.
=> feat: switch go-yaml implementation to most recent version

cloudformation/global/api.go, cloudformation/serverless/aws-serverless-api.go, generate/sam-2016-10-31.json
*Issue #, if available:* https://github.com/aws/aws-toolkit-vscode/issues/3102
Adds missing property `DisableExecuteApiEndpoint` to `AWS::Serverless::Api` resource type to schema that is documented in the schema here: https://github.com/awsdocs/aws-sam-developer-guide/blob/main/doc_source/sam-resource-api.md#user-content-sam-api-disableexecuteapiendpoint and implemented here: https://github.com/aws/serverless-application-model/blob/v1.57.0/samtranslator/schema/aws_serverless_api.py#L180
=> fix(schema): add DisableExecuteApiEndpoint to Serverless API

cloudformation/global/api.go, cloudformation/serverless/aws-serverless-api.go, generate/sam-2016-10-31.json
change serverless api model in schema from string to object according to docs and tested cli cmd 'aws sam validate'
#514
Change AWS::Serverless::Api Models schema type to object instead of string
=> feat(sam): serverless api model type fix

cloudformation/intrinsics.go, cloudformation/intrinsics_test.go
Currently, most intrinsics use string quoted encoded values. This prevents us from being able to nest intrinsics, although CloudFormation supports these statements natively.
This switches a few important intrinsics to use JSON encoding vs string quoting for encoded intrinsic values. This allows us to nest intrinsics.
Newly supported examples:
```golang
SelectPtr(0, GetAZs(""))
Select(2, Split("/", GetAtt("Bucket", "WebsiteURL")))
JoinPtr("", []string{
Sub("arn:aws:nnnnn:${AWS::Region}:${AWS::AccountId}:identity/"),
If(
"SomeAccount",
canonicalDomainName,
cloudformation.ImportValue(someOtherDomain),
),
})
```
=> feat(intrinsics): support nested intrinsics

cloudformation/template.go
*Issue #, if available:* #542
Marks optional fields as pointers so we can serialize/deserialize with confidence.
=> feat(template): support optional parameters

cloudformation/intrinsics.go, goformation_test.go
Adding support for FindInMap default value:
* https://aws.amazon.com/about-aws/whats-new/2023/01/aws-cloudformation-fnfindinmap-language-extension-default-values-additional-intrinsic-functions/
* https://github.com/aws-cloudformation/cfn-language-discussion/commit/42cec9ce0d980a0832dc0fd1aed5750980280892?short_path=be2a597
This probably would be breaking change because of additional parameter in a function
=> feat(intrinsics): add support for FindInMap default

intrinsics/tags.go
*Issue #, if available:* #554, #551
This PR fixes the short form intrinsics processor that would stop processing the children nodes.
=> fix(intrinsics): continue to process children when transforming

cloudformation/policies/policies.go
*Issue https://github.com/awslabs/goformation/issues/610*
Add support for specifying UseOnlineResharding UpdatePolicy for ElastiCache ReplicationGroup
=> feat(policies): add UseOnlineResharding update policy

.github/workflows/test_pull_request.yml, .github/workflows/update_schema.yml, devenv.nix, go.mod
*Description of changes:* This PR bumps the supported Golang versions to the three latest stable versions: 1.20 - 1.22.
=> feat: bump Golang versions
